### ISSUE TITLE
U.S. DOL Priorities & Industry Training Sector Icons

### ISSUE THREAD

**Issue by mmmohan** [jkhedani/taaccct#12]
Intuitively I want to click the icons and it will to take me somewhere

**Comment by billymeinke** [comment]
A fix may be to reduce the size of the icons so they appear less like "button" or things to be clicked.

Another solution would be to have a dialogue box appear on hover, explaining what the icon represents.

Thoughts, @jkhedani ?

**Comment by jkhedani** [comment]
I addressed a similar issue [here](https://github.com/jkhedani/taaccct/issues/13) in regards to the same icon set in the modal. I went ahead and reduced the size of the icons to see if we feel they are less "clickable":

![screen shot 2015-01-12 at 6 23 32 pm](https://cloud.githubusercontent.com/assets/1855878/5716030/5b4309f4-9a88-11e4-93eb-bd95c651dd93.png)

If we can think of useful text to go along with each icon, I'll append some popovers to house the content. My only worry is that additional text would be redundant due to the semiotic and descriptive nature of the icons and text themselves.

What do you folks think? @mmmohan @billymeinke

**Comment by billymeinke** [comment]
Ideally, we would reuse text form the DOL TACT website for the popovers...I'll have to look into that and see what is available.

@jkhedani As is, the icon resizing is effective for me in reducing the urge to click. I'll close this for now and we can revisit after the other main components are completed.
